### ISSUE TITLE
Nuget package does not target .NET Framework 4.x

### ISSUE THREAD

**Issue by behoyh** [michaelantoun/FluentSync#5]
Hi Michael,

As I understand this project is targeting .NET Standard 2.1, which breaks compatibility with .NET Framework 4.x. Is there any way I can submit a PR retargeting to .NET Standard 2.0 for .NET 4.x compat?

**Comment by michaelantoun** [comment]
I will look into it.

**Comment by michaelantoun** [comment]
I added support to .NET Framework 4.6.2 and higher in FluentSync v1.1.0.
